# Generated by Django 4.2.7 on 2024-05-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0004_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(upload_to='profile/%Y/%m/%d'),
        ),
    ]
